### PR TITLE
Fixed succesfull xml response from erroring

### PR DESCRIPTION
**Pull request by super-cache-money**
Otherwise in a report, it seems impossible to *not* get an error.

### CODE REVIEW

**Comment by ChrisAlvares** [comment]
You should not get an xml response in a report, it should be a CSV. Are you using a different output format than csv in the reporting interface?

**Comment by super-cache-money** [comment]
Oh, yeah, I was using `format: 'XML'`.

**Comment by ChrisAlvares** [comment]
Ah, I see. The only problem here is that this change will break anyone who is trying to use CSV reports, which is the default. You need to check the output format as well to make sure it is set to xml instead of changing the sign here.

```js
if (error || ('xml' !== report. format && -1 !== body.indexOf('<?xml'))) {
```

**Comment by ChrisAlvares** [comment]
fixed via #18

**Pull request closed without merging**
